# Ejercicios de Arrays y Matrices con NumPy

#### Ejercicio 1: Crear un array de 10 elementos con ceros.

In [21]:
import numpy as np

array_cero = np.zeros(10)
print(array_cero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Ejercicio 2: Genera un array con los números del 1 al 20.

In [37]:
array1_20 = np.arange(1, 21)
print(array1_20 )

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


#### Ejercicio 3: Crea un array con los números pares del 2 al 50.

In [39]:
array_par = np.arange(2, 51, 2)
print(array_par)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


#### Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.

In [43]:
matriz = np.random.rand(4, 4)
print(matriz)

[[0.21589114 0.17022689 0.67119495 0.11289183]
 [0.34073753 0.19420372 0.52914819 0.36078706]
 [0.83538133 0.02507991 0.82929494 0.27499115]
 [0.97874407 0.05157176 0.89041174 0.53824145]]


#### Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].

In [45]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
print(suma)

[5 7 9]


#### Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.

In [47]:
matriz_a = np.random.randint(1, 11, (3, 3))
matriz_b = np.random.randint(1, 11, (3, 3))

resultado = np.dot(matriz_a, matriz_b)

print("Matriz A:\n", matriz_a)
print("Matriz B:\n", matriz_b)
print("Resultado:\n", resultado)

Matriz A:
 [[8 4 2]
 [3 1 2]
 [1 1 6]]
Matriz B:
 [[ 2  2  5]
 [ 5  8  4]
 [ 3  2 10]]
Resultado:
 [[42 52 76]
 [17 18 39]
 [25 22 69]]


#### Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.

In [49]:
array = np.random.randint(1, 101, 15)

print("Array:", array)
print("Máximo:", array.max())
print("Mínimo:", array.min())
print("Promedio:", array.mean())

Array: [72 81 23  6 61 63 35  3 27 30 87 76 26 25 94]
Máximo: 94
Mínimo: 3
Promedio: 47.266666666666666


#### Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.

In [51]:
matriz = np.arange(1, 26).reshape(5, 5)

diagonal = np.diag(matriz)

print(matriz)
print("Diagonal:", diagonal)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


#### Ejercicio 10 : Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna

In [53]:
matriz = np.random.randint(1, 21, (5, 5))

suma_filas = matriz.sum(axis=1)
suma_columnas = matriz.sum(axis=0)

print("Matriz:\n", matriz)
print("Suma de filas:", suma_filas)
print("Suma de columnas:", suma_columnas)

Matriz:
 [[20  2  5 17 15]
 [ 5 14  7  5 15]
 [ 2  5 11  3  6]
 [ 2 17  8 18 11]
 [ 9 15 17 11  2]]
Suma de filas: [59 46 27 56 54]
Suma de columnas: [38 53 48 54 49]
